/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Main
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/OriginalMetadataCache.ts
var import_obsidian = require("obsidian");
async function initialize() {
  var _a;
  const uniqueFiles = Object.fromEntries(
    this.app.vault.getFiles().map((v) => [v.path, v])
  );
  await this._preload();
  const fileCache = this.fileCache;
  const metadataCache = this.metadataCache;
  setInterval(this.cleanupDeletedCache.bind(this), 6e5);
  let i = 0;
  const batchSize = 50;
  const pauseTime = 100;
  const notice = new Notice("Starting cache updating");
  for (const path in fileCache) {
    if (!path.endsWith(".md"))
      continue;
    if (fileCache.hasOwnProperty(path)) {
      const file = uniqueFiles[path];
      const cachedData = fileCache[path];
      if (file) {
        if (metadataCache.hasOwnProperty(cachedData.hash)) {
          if (import_obsidian.Platform.isAndroidApp && file.stat.mtime !== cachedData.mtime && cachedData.mtime % 1e3 === 0 && Math.floor(file.stat.mtime / 1e3) * 1e3 === cachedData.mtime) {
            cachedData.mtime = file.stat.mtime;
            this.saveFileCache(path, cachedData);
          }
          if (file.stat.mtime !== cachedData.mtime || file.stat.size !== cachedData.size) {
            notice.setMessage(`Computing ${i} - change`);
            await this.computeFileMetadataAsync(file);
            i++;
            if (i % batchSize === 0)
              await new Promise((r) => setTimeout(r, pauseTime));
          } else {
            (_a = this.linkResolverQueue) == null ? void 0 : _a.add(file);
          }
        } else {
          notice.setMessage(`Computing ${i} - insert`);
          await this.computeFileMetadataAsync(file);
          i++;
          if (i % batchSize === 0)
            await new Promise((r) => setTimeout(r, pauseTime));
        }
      } else {
        notice.setMessage(`Computing ${i} - delete`);
        this.deletePath(path);
      }
    }
  }
  for (const path in uniqueFiles) {
    if (uniqueFiles.hasOwnProperty(path) && !fileCache.hasOwnProperty(path)) {
      notice.setMessage(`Computing ${i} - create`);
      await this.computeFileMetadataAsync(uniqueFiles[path]);
      i++;
      if (i % batchSize === 0)
        await new Promise((r) => setTimeout(r, pauseTime));
    }
  }
  this.initialized = true;
  this.watchVaultChanges();
  this.updateUserIgnoreFilters();
  this.trigger("finished");
  setTimeout(() => {
    this.cleanupDeletedCache();
  }, 6e4);
}

// src/FSCache.ts
var import_obsidian2 = require("obsidian");
var FSCache = class {
  constructor(vaultPath) {
    this.db = null;
    this.flushEdits = (0, import_obsidian2.debounce)(
      (tree) => {
        return new Promise((resolve, reject) => {
          const request = this.getStore("readwrite").put(tree);
          request.onsuccess = () => {
            new Notice("Updated cache");
            resolve();
          };
          request.onerror = () => {
            reject(request.error);
          };
        });
      },
      1e3,
      true
    );
    this.inMemoryTree = emptyTree();
    this.dbName = "FSCache-" + vaultPath;
    this.storeName = "tree";
  }
  async init() {
    return new Promise((resolve, reject) => {
      const request = indexedDB.open(this.dbName, 4);
      let isUpgraded = false;
      request.onupgradeneeded = (event) => {
        isUpgraded = true;
        const db = event.target.result;
        if (db.objectStoreNames.contains(this.storeName)) {
          db.deleteObjectStore(this.storeName);
        }
        db.createObjectStore(this.storeName, {
          keyPath: "key"
        });
      };
      request.onsuccess = () => {
        this.db = request.result;
        if (isUpgraded) {
          void this.clearAll().then(() => {
            resolve(true);
          });
        } else
          resolve(false);
      };
      request.onerror = () => {
        reject(request.error);
      };
    });
  }
  getStore(mode) {
    if (!this.db)
      throw new Error("Database not initialized");
    return this.db.transaction(this.storeName, mode).objectStore(this.storeName);
  }
  getByPath(path) {
    if (path === "/")
      return this.inMemoryTree;
    let currentFolder = this.inMemoryTree;
    for (const section of path.split("/")) {
      if (!("children" in currentFolder))
        return void 0;
      const next = currentFolder.children[section];
      if (!next)
        return void 0;
      currentFolder = next;
    }
    return currentFolder;
  }
  addItem(parentPath, file, name) {
    const currentFolder = this.getByPath(parentPath);
    if (!currentFolder || !("children" in currentFolder) || name in currentFolder.children)
      return;
    currentFolder.children[name] = file;
    this.changeTree(this.inMemoryTree);
  }
  getItem(path) {
    return this.getByPath(path);
  }
  async getTree() {
    const tree = await new Promise((resolve, reject) => {
      const request = this.getStore("readonly").get("tree");
      request.onsuccess = () => {
        resolve(request.result);
      };
      request.onerror = () => {
        reject(request.error);
      };
    });
    this.inMemoryTree = tree;
    return tree;
  }
  changeTree(tree) {
    this.flushEdits(tree);
  }
  updateItem(parentPath, file, name) {
    const currentFolder = this.getByPath(parentPath);
    if (!currentFolder || !("children" in currentFolder) || !(name in currentFolder.children))
      return;
    currentFolder.children[name] = file;
    this.changeTree(this.inMemoryTree);
  }
  deleteItem(parentPath, name) {
    const currentFolder = this.getByPath(parentPath);
    if (!currentFolder || !("children" in currentFolder) || !(name in currentFolder.children))
      return;
    delete currentFolder.children[name];
    this.changeTree(this.inMemoryTree);
  }
  async clearAll() {
    return new Promise((resolve, reject) => {
      const request = this.getStore("readwrite").put(emptyTree());
      request.onsuccess = () => {
        resolve();
      };
      request.onerror = () => {
        reject(request.error);
      };
    });
  }
};
function emptyTree() {
  return { key: "tree", children: {} };
}

// node_modules/.pnpm/monkey-around@3.0.0/node_modules/monkey-around/dist/index.mjs
function around(obj, factories) {
  const removers = Object.keys(factories).map((key) => around1(obj, key, factories[key]));
  return removers.length === 1 ? removers[0] : function() {
    removers.forEach((r) => r());
  };
}
function around1(obj, method, createWrapper) {
  const inherited = obj[method], hadOwn = obj.hasOwnProperty(method), original = hadOwn ? inherited : function() {
    return Object.getPrototypeOf(obj)[method].apply(this, arguments);
  };
  let current = createWrapper(original);
  if (inherited)
    Object.setPrototypeOf(current, inherited);
  Object.setPrototypeOf(wrapper, current);
  obj[method] = wrapper;
  return remove;
  function wrapper(...args) {
    if (current === original && obj[method] === wrapper)
      remove();
    return current.apply(this, args);
  }
  function remove() {
    if (obj[method] === wrapper) {
      if (hadOwn)
        obj[method] = original;
      else
        delete obj[method];
    }
    if (current === original)
      return;
    current = original;
    Object.setPrototypeOf(wrapper, inherited || Function);
  }
}

// obsidian-reusables/src/PluginWithSettings.ts
var import_obsidian3 = require("obsidian");
function PluginWithSettings(DEFAULT_SETTINGS) {
  return class PluginWithSettings extends import_obsidian3.Plugin {
    constructor() {
      super(...arguments);
      this.settings = DEFAULT_SETTINGS;
      this.uninstallers = [];
    }
    async loadSettings() {
      Object.assign(this.settings, await this.loadData());
    }
    async initSettings(SettingsTab) {
      await this.loadSettings();
      this.addSettingTab(new SettingsTab(this.app, this));
    }
    async saveSettings() {
      await this.saveData(this.settings);
    }
    registerPatch(obj, factories) {
      const uninstaller = around(
        obj,
        // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
        Object.fromEntries(
          Object.entries(
            factories
          ).map(([key, f]) => {
            return [
              key,
              (next) => f(next, this)
            ];
          })
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
        )
      );
      this.uninstallers.push(uninstaller);
      return uninstaller;
    }
    uninstallPatches() {
      this.uninstallers.forEach((v) => {
        v();
      });
    }
    unload() {
      this.uninstallPatches();
    }
  };
}

// obsidian-reusables/src/indexFiles.ts
var import_obsidian4 = require("obsidian");
function getParentPath(p) {
  return p === "/" ? void 0 : p.split("/").slice(0, -1).join("/") || "/";
}

// src/settings.ts
var import_obsidian5 = require("obsidian");
var VirtualFSPluginSettingsTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian5.Setting(containerEl).setName("Cache management").setDesc("Manage vault cache").addButton(
      (button) => button.setButtonText("Clear cache").setCta().onClick(() => {
        var _a;
        void ((_a = this.plugin.fsCache) == null ? void 0 : _a.clearAll().then(() => {
          new Notice("Cleared cache!");
        }));
      })
    );
  }
};

// obsidian-typings/src/obsidian/implementations/Classes/CustomArrayDictImpl.ts
var CustomArrayDictImpl = class {
  constructor() {
    this.data = /* @__PURE__ */ new Map();
  }
  add(key, value) {
    let values = this.get(key);
    if (!values) {
      values = [];
      this.data.set(key, values);
    }
    if (!values.includes(value)) {
      values.push(value);
    }
  }
  remove(key, value) {
    const values = this.get(key);
    if (!values) {
      return;
    }
    values.remove(value);
    if (values.length === 0) {
      this.clear(key);
    }
  }
  get(key) {
    return this.data.get(key) || null;
  }
  keys() {
    return Array.from(this.data.keys());
  }
  clear(key) {
    this.data.delete(key);
  }
  clearAll() {
    this.data.clear();
  }
  contains(key, value) {
    var _a;
    return !!((_a = this.get(key)) == null ? void 0 : _a.contains(value));
  }
  count() {
    var _a, _b;
    let ans = 0;
    for (const key in this.keys()) {
      ans += (_b = (_a = this.get(key)) == null ? void 0 : _a.length) != null ? _b : 0;
    }
    return ans;
  }
};

// src/main.ts
var Main = class extends PluginWithSettings({}) {
  constructor() {
    super(...arguments);
    this.setupListenersForCache = (fsCache) => {
      const createFileInFSCache = (file) => {
        if (file.parent)
          fsCache.addItem(
            file.parent.path,
            file instanceof import_obsidian6.TFile ? {
              size: file.stat.size,
              mtime: file.stat.mtime,
              ctime: file.stat.ctime
            } : {
              children: {}
            },
            file.name
          );
      };
      this.registerEvent(
        this.app.vault.on("create", (file) => {
          createFileInFSCache(file);
        })
      );
      this.registerEvent(
        this.app.vault.on("delete", (file) => {
          if (file.path !== "/")
            fsCache.deleteItem(getParentPath(file.path), file.name);
        })
      );
      this.registerEvent(
        this.app.vault.on("rename", (file, oldPath) => {
          var _a, _b;
          const old = fsCache.getItem(oldPath);
          const parentpath = oldPath.split("/").slice(0, -1).join("/") || "/";
          const name = oldPath.split("/").at(-1);
          fsCache.deleteItem(parentpath, name);
          if (old)
            fsCache.addItem((_b = (_a = file.parent) == null ? void 0 : _a.path) != null ? _b : "/", old, file.name);
          else
            createFileInFSCache(file);
        })
      );
    };
    this.reconcileNode = (node) => {
      this.app.vault.adapter.files[node.path] = {
        type: "size" in node ? "file" : "folder",
        realpath: node.path
      };
      const existing = this.app.vault.fileMap[node.path];
      if (existing) {
        if ("size" in node) {
          if (existing instanceof import_obsidian6.TFolder)
            this.app.vault.onChange("folder-removed", node.path);
          else
            return;
        } else {
          if (existing instanceof import_obsidian6.TFile)
            this.app.vault.onChange("file-removed", node.path);
          else if (existing instanceof import_obsidian6.TFolder) {
            const newByName = new Set(node.children.map((v) => v.name));
            for (const child of existing.children) {
              const wasDeleted = !newByName.has(child.name);
              const isVirtual = child instanceof import_obsidian6.TFile && child.extension === "dir";
              if (wasDeleted && !isVirtual)
                this.app.vault.onChange("file-removed", child.path);
            }
            return;
          }
        }
      }
      if ("size" in node) {
        this.app.vault.onChange("file-created", node.path, void 0, node);
        const file = this.app.vault.fileMap[node.path];
        if (file instanceof import_obsidian6.TFile)
          this.app.metadataCache.uniqueFileLookup.add(
            file.name.toLowerCase(),
            file
          );
      } else
        this.app.vault.onChange("folder-created", node.path);
    };
  }
  async onload() {
    await this.initSettings(VirtualFSPluginSettingsTab);
    this.app.metadataCache.initialize = async () => {
    };
    this.patchNodeFSAdapter();
    this.patchCapacitorFSAdapter();
  }
  patchCapacitorFSAdapter() {
    this.registerPatch(import_obsidian6.CapacitorAdapter.prototype, {
      watchAndList(_, plugin) {
        return async function() {
          const readDir = async (p) => {
            const children = await this.fs.readdir(p);
            return children.map((v) => {
              var _a, _b, _c;
              return {
                name: v.name,
                type: v.type === "directory" ? "folder" : "file",
                ctime: (_a = v.ctime) != null ? _a : 0,
                mtime: (_b = v.mtime) != null ? _b : 0,
                size: (_c = v.size) != null ? _c : 0
              };
            });
          };
          await plugin.lazyLoad(readDir);
        };
      }
    });
  }
  patchNodeFSAdapter() {
    this.registerPatch(import_obsidian6.FileSystemAdapter.prototype, {
      listAll(_, plugin) {
        return async function() {
          const readDir = async (p) => {
            const children = await this.fsPromises.readdir(p, {
              withFileTypes: true
            });
            const promises = children.map(async (v) => {
              const stats = await this.fsPromises.stat(
                p + "/" + v.name
              );
              return {
                name: v.name,
                type: v.isDirectory() ? "folder" : "file",
                ctime: stats.ctime.valueOf(),
                mtime: stats.mtime.valueOf(),
                size: stats.size
              };
            });
            return Promise.all(promises);
          };
          await plugin.lazyLoad(readDir);
        };
      }
    });
  }
  async lazyLoad(readdir) {
    const adapter = this.app.vault.adapter;
    const fsCache = new FSCache(adapter.basePath);
    this.fsCache = fsCache;
    console.time("reading cache");
    const wasInitialised = await fsCache.init();
    const tree = await fsCache.getTree();
    console.timeEnd("reading cache");
    const wasEmpty = wasInitialised || Object.keys(tree.children).length === 0;
    const otherHandlers = this.app.vault._;
    this.app.vault._ = {};
    console.time("applying cache");
    this.visitCachedNodes(tree, this.reconcileNode, "/");
    console.timeEnd("applying cache");
    this.app.vault._ = otherHandlers;
    this.setupListenersForCache(fsCache);
    const reconcilePromise = this.visitRealNodes(
      "/",
      this.reconcileNode,
      readdir,
      wasEmpty ? void 0 : 10
    );
    const updateMetadataCache = async () => {
      console.time("metadata");
      await initialize.bind(this.app.metadataCache)();
      console.timeEnd("metadata");
    };
    const updateFile = (file) => {
      var _a, _b, _c, _d, _e, _f, _g, _h;
      for (const [target] of (_a = file.links) != null ? _a : []) {
        (_b = target.backlinks) == null ? void 0 : _b.delete(file);
      }
      const cache = this.app.metadataCache.getFileCache(file);
      if (cache) {
        (_c = file.links) != null ? _c : file.links = /* @__PURE__ */ new Map();
        for (const link of [
          ...(_d = cache.links) != null ? _d : [],
          ...(_e = cache.frontmatterLinks) != null ? _e : []
        ]) {
          const target = this.app.metadataCache.getFirstLinkpathDest(
            link.link,
            file.path
          );
          if (!target)
            continue;
          (_f = target.backlinks) != null ? _f : target.backlinks = /* @__PURE__ */ new Map();
          const refs = (_g = target.backlinks.get(file)) != null ? _g : [];
          refs.push(link);
          target.backlinks.set(file, refs);
          const outRefs = (_h = file.links.get(target)) != null ? _h : [];
          outRefs.push(link);
          file.links.set(target, outRefs);
        }
      }
    };
    const updateBacklinks = async () => {
      const notice = new Notice("Starting filling backlinks", 1e5);
      console.time("backlinks");
      const files = this.app.vault.getFiles();
      for (let i = 0; i < files.length; i++) {
        const file = files[i];
        if (file)
          updateFile(file);
        if (i % 100 === 0)
          await new Promise((r) => setTimeout(r, 1));
      }
      console.timeEnd("backlinks");
      notice.setMessage("Finished filling backlinks");
      setTimeout(() => {
        notice.hide();
      }, 2e3);
    };
    const bindFileWatchers = adapter instanceof import_obsidian6.FileSystemAdapter ? async () => {
      const notice = new Notice(
        "Starting setting watches",
        1e5
      );
      console.time("watches");
      const files = Object.keys(adapter.files);
      for (let i = 0; i < files.length; i++) {
        const file = files[i];
        await adapter.startWatchPath(file);
        if (i % 20 === 0)
          await new Promise((r) => setTimeout(r, 20));
      }
      console.timeEnd("watches");
      notice.setMessage("Finished setting watches");
      setTimeout(() => {
        notice.hide();
      }, 2e3);
    } : async () => {
    };
    if (wasEmpty) {
      console.time("filling cache");
      await reconcilePromise;
      console.timeEnd("filling cache");
      void updateMetadataCache().then(updateBacklinks).then(bindFileWatchers);
    } else {
      console.time("updating cache");
      void updateBacklinks();
      void reconcilePromise.then(() => {
        console.timeEnd("updating cache");
      }).then(updateMetadataCache).then(bindFileWatchers);
    }
    this.app.metadataCache.on("resolve", (file) => {
      updateFile(file);
    });
    this.app.metadataCache.on("changed", (file) => {
      updateFile(file);
    });
    this.app.vault.on("delete", (file) => {
      var _a, _b;
      if (file instanceof import_obsidian6.TFile)
        for (const [target] of (_a = file.links) != null ? _a : []) {
          (_b = target.backlinks) == null ? void 0 : _b.delete(file);
        }
    });
    this.registerPatch(this.app.metadataCache, {
      getBacklinksForFile() {
        return (file) => {
          var _a, _b;
          const dict = new CustomArrayDictImpl();
          dict.data = new Map(
            [...(_b = (_a = file.backlinks) == null ? void 0 : _a.entries()) != null ? _b : []].map(([k, v]) => [
              k.path,
              v
            ])
          );
          return dict;
        };
      }
    });
    return fsCache;
  }
  visitCachedNodes(tree, visitor, path) {
    visitor({
      type: "folder",
      path,
      children: Object.entries(tree.children).map(
        ([name, v]) => "children" in v ? { type: "folder", name } : { type: "file", name }
      )
    });
    for (const [name, child] of Object.entries(tree.children)) {
      const nextPath = path === "/" ? name : `${path}/${name}`;
      if ("children" in child) {
        this.visitCachedNodes(child, visitor, nextPath);
      } else {
        visitor({
          type: "file",
          path: nextPath,
          ctime: child.ctime,
          mtime: child.mtime,
          size: child.size
        });
      }
    }
  }
  async visitRealNodes(p, visitor, readdir, timeout) {
    const base = this.app.vault.adapter.basePath;
    const fullPath = p === "/" ? base : base + "/" + p;
    const children = await readdir(fullPath);
    if (timeout !== void 0)
      await new Promise((r) => setTimeout(r, timeout));
    visitor({ type: "folder", path: p, children });
    for (const c of children) {
      const nextPath = p === "/" ? c.name : `${p}/${c.name}`;
      if (c.name.startsWith("."))
        continue;
      if (c.type === "folder") {
        await this.visitRealNodes(nextPath, visitor, readdir);
      } else {
        visitor({
          type: "file",
          path: nextPath,
          ctime: c.ctime,
          mtime: c.mtime,
          size: c.size
        });
      }
    }
  }
};
