/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ConsecutiveLists
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var ConsecutiveLists = class extends import_obsidian.Plugin {
  async onload() {
    function isListElement(line) {
      const listPrefixes = ["- ", "+ ", "* "];
      line = line.trimStart();
      return listPrefixes.some((prefix) => line.startsWith(prefix));
    }
    function isFirstListElement(editor, lineNumber) {
      if (isListElement(editor.getLine(lineNumber))) {
        if (lineNumber == 0) {
          return true;
        } else {
          return !isListElement(editor.getLine(lineNumber - 1));
        }
      } else {
        return false;
      }
    }
    function getPreviousListCharacter(editor, lineNumber) {
      lineNumber -= 1;
      while (lineNumber >= 0) {
        const line = editor.getLine(lineNumber);
        if (isListElement(line)) {
          return line.trimStart()[0];
        } else if (line == "") {
          lineNumber -= 1;
          continue;
        } else {
          return null;
        }
      }
      return null;
    }
    this.registerDomEvent(document, "keyup", () => {
      var _a;
      const editor = (_a = this.app.workspace.activeEditor) == null ? void 0 : _a.editor;
      if (editor !== void 0) {
        const lineNumber = editor.getCursor().line;
        const line = editor.getLine(lineNumber);
        if (isFirstListElement(editor, lineNumber)) {
          const prevListPrefix = getPreviousListCharacter(editor, lineNumber);
          if (prevListPrefix != null) {
            if (prevListPrefix == "-" && line.startsWith("-")) {
              editor.setLine(lineNumber, line.replace("-", "+"));
            }
          }
        }
      }
    });
  }
};

/* nosourcemap */