/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NodeFactor
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  fwdMultiplier: 1,
  fwdTree: false,
  bwdMultiplier: 1,
  lettersPerWt: 0
};

// src/settings.ts
var import_obsidian = require("obsidian");
var SampleSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Forward link weight multiplier").setDesc("Multiplier for forward links weight (0 to diable).").addSlider(
      (slider) => slider.setLimits(0, 20, 1).setDynamicTooltip().setValue(this.plugin.settings.fwdMultiplier).onChange(async (value) => {
        this.plugin.settings.fwdMultiplier = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Travel forward tree").setDesc("Travel forward tree to calcuate node size.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.fwdTree).onChange(async (value) => {
        this.plugin.settings.fwdTree = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Backward link weight multiplier").setDesc("Multiplier for backward links weight (0 to diable).").addSlider(
      (slider) => slider.setLimits(0, 20, 1).setDynamicTooltip().setValue(this.plugin.settings.bwdMultiplier).onChange(async (value) => {
        this.plugin.settings.bwdMultiplier = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Character per weight").setDesc(
      "Add 1 weight to node size per no of given Character (0 to disable)."
    ).addSlider(
      (slider) => slider.setLimits(0, 5e3, 100).setDynamicTooltip().setValue(this.plugin.settings.lettersPerWt).onChange(async (value) => {
        this.plugin.settings.lettersPerWt = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var NodeFactor = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    // This is a hash map that helps in specifically optimizing the forward tree
    this.treeOptimizeMap = /* @__PURE__ */ new Map();
    // This array helps in optimizing the whole calculation process
    this.storedSized = [];
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SampleSettingTab(this.app, this));
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        const leaf = this.app.workspace.getLeavesOfType("graph").first();
        if (!leaf) {
          this.updateLoop = false;
          return;
        }
        this.updateLoop = true;
        const nodes = leaf.view.renderer.nodes;
        if (nodes.length === 0)
          return;
        this.calcLoop(nodes);
      })
    );
    this.registerEvent(
      this.app.vault.on("create", () => this.storedSized = [])
    );
    this.registerEvent(
      this.app.vault.on("modify", () => this.storedSized = [])
    );
    this.registerEvent(
      this.app.vault.on("delete", () => this.storedSized = [])
    );
    this.registerEvent(
      this.app.vault.on("rename", () => this.storedSized = [])
    );
  }
  async onunload() {
    this.updateLoop = false;
  }
  calcLoop(nodes) {
    setTimeout(() => {
      this.updateNodes(nodes);
      if (this.updateLoop)
        this.calcLoop(nodes);
    }, 10);
  }
  updateNodes(nodes) {
    this.treeOptimizeMap.clear();
    nodes.forEach((node, i) => {
      let weight;
      if (this.storedSized[i] != void 0) {
        weight = this.storedSized[i];
      } else {
        weight = this.calcNodeWeight(node);
        this.storedSized[i] = weight;
      }
      node.weight = weight;
    });
  }
  calcNodeWeight(node) {
    const settings = this.settings;
    let weight = 0;
    weight += Object.keys(node.reverse).length * settings.bwdMultiplier;
    if (settings.fwdTree) {
      weight += this.fwdNodeTreeSize(node, node.id) * settings.fwdMultiplier;
    } else {
      weight += Object.keys(node.forward).length * settings.fwdMultiplier;
    }
    if (settings.lettersPerWt != 0) {
      weight += this.letterCount(node) / settings.lettersPerWt;
    }
    return Math.round(weight);
  }
  letterCount(node) {
    const file = this.app.vault.getFileByPath(node.id);
    if (!file || file.extension != "md")
      return 0;
    return file.stat.size;
  }
  fwdNodeTreeSize(node, id) {
    let size = 0;
    const sizeMap = this.treeOptimizeMap.get(node.id);
    if (sizeMap !== void 0) {
      return sizeMap;
    }
    Object.entries(node.forward).forEach(([key, value]) => {
      const childNode = value.target;
      if (key === id)
        return size;
      size++;
      const childSize = this.fwdNodeTreeSize(childNode, id);
      size += childSize;
    });
    this.treeOptimizeMap.set(node.id, size);
    return size;
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};


/* nosourcemap */